// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";

export type Ingredient = {
  name: string;
  effects: string[];
  obtained: string;
  value: number;
  weight: number;
  plantable: boolean;
  fishable: boolean;
};

export const ingredients: Ingredient[] = [
  {
    name: "Abecean Longfin",
    effects: [
      "Weakness to Frost",
      "Fortify Sneak",
      "Weakness to Poison",
      "Fortify Restoration",
    ],
    obtained: "Lakes, rivers, streams, fish barrels",
    value: 15,
    weight: 0.5,
    plantable: false,
    fishable: true,
  },
  {
    name: "Ancestor Moth Wing",
    effects: [
      "Damage Stamina",
      "Fortify Conjuration",
      "Damage Magicka Regen",
      "Fortify Enchanting",
    ],
    obtained: "Ancestor Glade",
    value: 2,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Ash Creep Cluster",
    effects: [
      "Damage Stamina",
      "Invisibility",
      "Resist Fire",
      "Fortify Destruction",
    ],
    obtained: "Harvested from ash covered areas of Solstheim",
    value: 20,
    weight: 0.3,
    plantable: false,
    fishable: false,
  },
  {
    name: "Ash Hopper Jelly",
    effects: [
      "Restore Health",
      "Fortify Light Armor",
      "Resist Shock",
      "Weakness to Frost",
    ],
    obtained: "Ash Hopper Corpses",
    value: 20,
    weight: 0.3,
    plantable: false,
    fishable: false,
  },
  {
    name: "Ashen Grass Pod",
    effects: [
      "Resist Fire",
      "Weakness to Shock",
      "Fortify Lockpicking",
      "Fortify Sneak",
    ],
    obtained: "Harvested from ash covered areas of Solstheim",
    value: 1,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Bear Claws",
    effects: [
      "Restore Stamina",
      "Fortify Health",
      "Fortify One-Handed",
      "Damage Magicka Regen",
    ],
    obtained: "Bears, Cave Bears, Snow Bears",
    value: 2,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Bee",
    effects: [
      "Restore Stamina",
      "Ravage Stamina",
      "Regenerate Stamina",
      "Weakness to Shock",
    ],
    obtained: "Beehive",
    value: 3,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Beehive Husk",
    effects: [
      "Resist Poison",
      "Fortify Light Armor",
      "Fortify Sneak",
      "Fortify Destruction",
    ],
    obtained: "Beehive",
    value: 5,
    weight: 1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Berit's Ashes (identical to Bone Meal)",
    effects: [
      "Damage Stamina",
      "Resist Fire",
      "Fortify Conjuration",
      "Ravage Stamina",
    ],
    obtained:
      "Quest item given by Thadgeir; also found in Valerica's Study in Castle Volkihar.",
    value: 5,
    weight: 0.5,
    plantable: false,
    fishable: false,
  },
  {
    name: "Bleeding Crown",
    effects: [
      "Weakness to Fire",
      "Fortify Block",
      "Weakness to Poison",
      "Resist Magic",
    ],
    obtained: "Mushroom clusters",
    value: 10,
    weight: 0.3,
    plantable: true,
    fishable: false,
  },
  {
    name: "Blisterwort",
    effects: ["Damage Stamina", "Frenzy", "Restore Health", "Fortify Smithing"],
    obtained: "Caves and dark areas",
    value: 12,
    weight: 0.2,
    plantable: true,
    fishable: false,
  },
  {
    name: "Blue Butterfly Wing",
    effects: [
      "Damage Stamina",
      "Fortify Conjuration",
      "Damage Magicka Regen",
      "Fortify Enchanting",
    ],
    obtained: "Blue Butterfly",
    value: 2,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Blue Dartwing",
    effects: ["Resist Shock", "Fortify Pickpocket", "Restore Health", "Fear"],
    obtained: "Hovering above water",
    value: 1,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Blue Mountain Flower",
    effects: [
      "Restore Health",
      "Fortify Conjuration",
      "Fortify Health",
      "Damage Magicka Regen",
    ],
    obtained: "Mountain flower clumps",
    value: 2,
    weight: 0.1,
    plantable: true,
    fishable: false,
  },
  {
    name: "Boar Tusk",
    effects: ["Fortify Stamina", "Fortify Health", "Fortify Block", "Frenzy"],
    obtained: "Bristlebacks",
    value: 20,
    weight: 0.5,
    plantable: false,
    fishable: false,
  },
  {
    name: "Bone Meal",
    effects: [
      "Damage Stamina",
      "Resist Fire",
      "Fortify Conjuration",
      "Ravage Stamina",
    ],
    obtained: "Draugr and skeletons",
    value: 5,
    weight: 0.5,
    plantable: false,
    fishable: false,
  },
  {
    name: "Briar Heart",
    effects: [
      "Restore Magicka",
      "Fortify Block",
      "Paralysis",
      "Fortify Magicka",
    ],
    obtained: "Forsworn Leaders",
    value: 20,
    weight: 0.5,
    plantable: false,
    fishable: false,
  },
  {
    name: "Burnt Spriggan Wood",
    effects: [
      "Weakness to Fire",
      "Fortify Alteration",
      "Damage Magicka Regen",
      "Slow",
    ],
    obtained: "Burnt Spriggans",
    value: 20,
    weight: 0.5,
    plantable: false,
    fishable: false,
  },
  {
    name: "Butterfly Wing",
    effects: [
      "Restore Health",
      "Fortify Barter",
      "Lingering Damage Stamina",
      "Damage Magicka",
    ],
    obtained: "Monarch Butterfly",
    value: 3,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Canis Root",
    effects: [
      "Damage Stamina",
      "Fortify One-Handed",
      "Fortify Marksman",
      "Paralysis",
    ],
    obtained: "Near rocky areas",
    value: 5,
    weight: 0.1,
    plantable: true,
    fishable: false,
  },
  {
    name: "Charred Skeever Hide",
    effects: [
      "Restore Stamina",
      "Cure Disease",
      "Resist Poison",
      "Restore Health",
    ],
    obtained: "Found at campfires",
    value: 1,
    weight: 0.5,
    plantable: false,
    fishable: false,
  },
  {
    name: "Chaurus Eggs",
    effects: [
      "Weakness to Poison",
      "Fortify Stamina",
      "Damage Magicka",
      "Invisibility",
    ],
    obtained: "Falmer caves",
    value: 10,
    weight: 0.2,
    plantable: false,
    fishable: false,
  },
  {
    name: "Chaurus Hunter Antennae",
    effects: [
      "Damage Stamina",
      "Fortify Conjuration",
      "Damage Magicka Regen",
      "Fortify Enchanting",
    ],
    obtained: "Chaurus Hunter, Chaurus Hunter Fledgling",
    value: 2,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Chicken's Egg",
    effects: [
      "Resist Magic",
      "Damage Magicka Regen",
      "Waterbreathing",
      "Lingering Damage Stamina",
    ],
    obtained: "Chicken's Nest",
    value: 2,
    weight: 0.5,
    plantable: false,
    fishable: false,
  },
  {
    name: "Creep Cluster",
    effects: [
      "Restore Magicka",
      "Damage Stamina Regen",
      "Fortify Carry Weight",
      "Weakness to Magic",
    ],
    obtained: "Hydro-thermal areas",
    value: 1,
    weight: 0.2,
    plantable: true,
    fishable: false,
  },
  {
    name: "Crimson Nirnroot",
    effects: [
      "Damage Health",
      "Damage Stamina",
      "Invisibility",
      "Resist Magic",
    ],
    obtained: "Blackreach",
    value: 10,
    weight: 0.2,
    plantable: false,
    fishable: false,
  },
  {
    name: "Cyrodilic Spadetail",
    effects: ["Damage Stamina", "Fortify Restoration", "Fear", "Ravage Health"],
    obtained: "Lakes, rivers, streams, fish barrels",
    value: 15,
    weight: 0.3,
    plantable: false,
    fishable: true,
  },
  {
    name: "Daedra Heart",
    effects: [
      "Restore Health",
      "Damage Stamina Regen",
      "Damage Magicka",
      "Fear",
    ],
    obtained: "Daedra",
    value: 250,
    weight: 0.5,
    plantable: false,
    fishable: false,
  },
  {
    name: "Deathbell",
    effects: ["Damage Health", "Ravage Stamina", "Slow", "Weakness to Poison"],
    obtained: "Wild, on planters",
    value: 4,
    weight: 0.1,
    plantable: true,
    fishable: false,
  },
  {
    name: "Dragon's Tongue",
    effects: [
      "Resist Fire",
      "Fortify Barter",
      "Fortify Illusion",
      "Fortify Two-Handed",
    ],
    obtained: "Hydro-thermal areas",
    value: 5,
    weight: 0.1,
    plantable: true,
    fishable: false,
  },
  {
    name: "Dwarven Oil",
    effects: [
      "Weakness to Magic",
      "Fortify Illusion",
      "Regenerate Magicka",
      "Restore Magicka",
    ],
    obtained: "Dwemer Ruins",
    value: 15,
    weight: 0.3,
    plantable: false,
    fishable: false,
  },
  {
    name: "Ectoplasm",
    effects: [
      "Restore Magicka",
      "Fortify Destruction",
      "Fortify Magicka",
      "Damage Health",
    ],
    obtained: "Ghostlike creatures",
    value: 25,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Elves Ear",
    effects: [
      "Restore Magicka",
      "Fortify Marksman",
      "Weakness to Frost",
      "Resist Fire",
    ],
    obtained: "Plant, hanging herbs",
    value: 10,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Emperor Parasol Moss",
    effects: [
      "Damage Health",
      "Fortify Magicka",
      "Regenerate Health",
      "Fortify Two-Handed",
    ],
    obtained: "Hanging from Emperor Parasol around Tel Mithryn.",
    value: 1,
    weight: 0.3,
    plantable: false,
    fishable: false,
  },
  {
    name: "Eye of Sabre Cat",
    effects: [
      "Restore Stamina",
      "Ravage Health",
      "Damage Magicka",
      "Restore Health",
    ],
    obtained: "Sabre Cat, Snowy Sabre Cat",
    value: 2,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Falmer Ear",
    effects: [
      "Damage Health",
      "Frenzy",
      "Resist Poison",
      "Fortify Lockpicking",
    ],
    obtained: "Falmer",
    value: 10,
    weight: 0.2,
    plantable: false,
    fishable: false,
  },
  {
    name: "Felsaad Tern Feathers",
    effects: [
      "Restore Health",
      "Fortify Light Armor",
      "Cure Disease",
      "Resist Magic",
    ],
    obtained: "Felsaad Tern",
    value: 15,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Fire Salts",
    effects: [
      "Weakness to Frost",
      "Resist Fire",
      "Restore Magicka",
      "Regenerate Magicka",
    ],
    obtained: "Flame Atronach",
    value: 50,
    weight: 0.3,
    plantable: false,
    fishable: false,
  },
  {
    name: "Fly Amanita",
    effects: [
      "Resist Fire",
      "Fortify Two-Handed",
      "Frenzy",
      "Regenerate Stamina",
    ],
    obtained: "Mushroom clusters in and around caves",
    value: 2,
    weight: 0.1,
    plantable: true,
    fishable: false,
  },
  {
    name: "Frost Mirriam",
    effects: [
      "Resist Frost",
      "Fortify Sneak",
      "Ravage Magicka",
      "Damage Stamina Regen",
    ],
    obtained: "Hanging in homes, businesses and giant camps",
    value: 1,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Frost Salts",
    effects: [
      "Weakness to Fire",
      "Resist Frost",
      "Restore Magicka",
      "Fortify Conjuration",
    ],
    obtained: "Frost Atronach",
    value: 100,
    weight: 0.3,
    plantable: false,
    fishable: false,
  },
  {
    name: "Garlic",
    effects: [
      "Resist Poison",
      "Fortify Stamina",
      "Regenerate Magicka",
      "Regenerate Health",
    ],
    obtained: "Hanging in homes, businesses and cooking areas",
    value: 1,
    weight: 0.3,
    plantable: false,
    fishable: false,
  },
  {
    name: "Giant Lichen",
    effects: [
      "Weakness to Shock",
      "Ravage Health",
      "Weakness to Poison",
      "Restore Magicka",
    ],
    obtained: "Swamps",
    value: 5,
    weight: 0.3,
    plantable: true,
    fishable: false,
  },
  {
    name: "Giant's Toe",
    effects: [
      "Damage Stamina",
      "Fortify Health",
      "Fortify Carry Weight",
      "Damage Stamina Regen",
    ],
    obtained: "Giants",
    value: 20,
    weight: 1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Gleamblossom",
    effects: ["Resist Magic", "Fear", "Regenerate Health", "Paralysis"],
    obtained: "Harvested in Darkfall Cave, Forgotten Vale",
    value: 5,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Glow Dust",
    effects: [
      "Damage Magicka",
      "Damage Magicka Regen",
      "Fortify Destruction",
      "Resist Shock",
    ],
    obtained: "Wispmother",
    value: 20,
    weight: 0.5,
    plantable: false,
    fishable: false,
  },
  {
    name: "Glowing Mushroom",
    effects: [
      "Resist Shock",
      "Fortify Destruction",
      "Fortify Smithing",
      "Fortify Health",
    ],
    obtained: "Caves, Dwemer Ruins",
    value: 5,
    weight: 0.2,
    plantable: true,
    fishable: false,
  },
  {
    name: "Grass Pod",
    effects: [
      "Resist Poison",
      "Ravage Magicka",
      "Fortify Alteration",
      "Restore Magicka",
    ],
    obtained: "Tundras",
    value: 1,
    weight: 0.1,
    plantable: true,
    fishable: false,
  },
  {
    name: "Hagraven Claw",
    effects: [
      "Resist Magic",
      "Lingering Damage Magicka",
      "Fortify Enchanting",
      "Fortify Barter",
    ],
    obtained: "Hagraven",
    value: 20,
    weight: 0.3,
    plantable: false,
    fishable: false,
  },
  {
    name: "Hagraven Feathers",
    effects: [
      "Damage Magicka",
      "Fortify Conjuration",
      "Frenzy",
      "Weakness to Shock",
    ],
    obtained: "Hagraven",
    value: 20,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Hanging Moss",
    effects: [
      "Damage Magicka",
      "Fortify Health",
      "Damage Magicka Regen",
      "Fortify One-Handed",
    ],
    obtained: "Vegetated areas, hanging in caves, from buildings",
    value: 1,
    weight: 0.3,
    plantable: false,
    fishable: false,
  },
  {
    name: "Hawk Beak",
    effects: [
      "Restore Stamina",
      "Resist Frost",
      "Fortify Carry Weight",
      "Resist Shock",
    ],
    obtained: "Hawks",
    value: 15,
    weight: 0.3,
    plantable: false,
    fishable: false,
  },
  {
    name: "Hawk Feathers",
    effects: [
      "Cure Disease",
      "Fortify Light Armor",
      "Fortify One-Handed",
      "Fortify Sneak",
    ],
    obtained: "Hawks",
    value: 15,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Hawk's Egg†",
    effects: [
      "Resist Magic",
      "Damage Magicka Regen",
      "Waterbreathing",
      "Lingering Damage Stamina",
    ],
    obtained: "Hawk's Nest",
    value: 2,
    weight: 0.5,
    plantable: false,
    fishable: false,
  },
  {
    name: "Histcarp",
    effects: [
      "Restore Stamina",
      "Fortify Magicka",
      "Damage Stamina Regen",
      "Waterbreathing",
    ],
    obtained: "Lakes, rivers, streams and fish barrels",
    value: 6,
    weight: 0.3,
    plantable: false,
    fishable: true,
  },
  {
    name: "Honeycomb",
    effects: [
      "Restore Stamina",
      "Fortify Block",
      "Fortify Light Armor",
      "Ravage Stamina",
    ],
    obtained: "Beehive",
    value: 5,
    weight: 1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Human Flesh",
    effects: ["Damage Health", "Paralysis", "Restore Magicka", "Fortify Sneak"],
    obtained: "Falmer Vampire dens",
    value: 1,
    weight: 0.3,
    plantable: false,
    fishable: false,
  },
  {
    name: "Human Heart",
    effects: [
      "Damage Health",
      "Damage Magicka",
      "Damage Magicka Regen",
      "Frenzy",
    ],
    obtained: "Falmer Vampire dens",
    value: 0,
    weight: 1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Ice Wraith Teeth",
    effects: [
      "Weakness to Frost",
      "Fortify Heavy Armor",
      "Invisibility",
      "Weakness to Fire",
    ],
    obtained: "Ice Wraith",
    value: 30,
    weight: 0.3,
    plantable: false,
    fishable: false,
  },
  {
    name: "Imp Stool",
    effects: [
      "Damage Health",
      "Lingering Damage Health",
      "Paralysis",
      "Restore Health",
    ],
    obtained: "Mushroom clusters near caves or dungeons",
    value: 0,
    weight: 0.3,
    plantable: true,
    fishable: false,
  },
  {
    name: "Jarrin Root",
    effects: [
      "Damage Health",
      "Damage Magicka",
      "Damage Stamina",
      "Damage Magicka Regen",
    ],
    obtained: "Dark Brotherhood quest",
    value: 10,
    weight: 0.5,
    plantable: false,
    fishable: false,
  },
  {
    name: "Jazbay Grapes",
    effects: [
      "Weakness to Magic",
      "Fortify Magicka",
      "Regenerate Magicka",
      "Ravage Health",
    ],
    obtained: "Hydro-thermal regions",
    value: 1,
    weight: 0.2,
    plantable: true,
    fishable: false,
  },
  {
    name: "Juniper Berries",
    effects: [
      "Weakness to Fire",
      "Fortify Marksman",
      "Regenerate Health",
      "Damage Stamina Regen",
    ],
    obtained: "Juniper Trees",
    value: 1,
    weight: 0.1,
    plantable: true,
    fishable: false,
  },
  {
    name: "Large Antlers",
    effects: [
      "Restore Stamina",
      "Fortify Stamina",
      "Slow",
      "Damage Stamina Regen",
    ],
    obtained: "Deer, Elk",
    value: 2,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Lavender",
    effects: [
      "Resist Magic",
      "Fortify Stamina",
      "Ravage Magicka",
      "Fortify Conjuration",
    ],
    obtained: "Outdoors in clumps",
    value: 1,
    weight: 0.1,
    plantable: true,
    fishable: false,
  },
  {
    name: "Luna Moth Wing",
    effects: [
      "Damage Magicka",
      "Fortify Light Armor",
      "Regenerate Health",
      "Invisibility",
    ],
    obtained: "Luna Moth",
    value: 5,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Moon Sugar",
    effects: [
      "Weakness to Fire",
      "Resist Frost",
      "Restore Magicka",
      "Regenerate Magicka",
    ],
    obtained: "Khajiit Caravans",
    value: 50,
    weight: 0.3,
    plantable: false,
    fishable: false,
  },
  {
    name: "Mora Tapinella",
    effects: [
      "Restore Magicka",
      "Lingering Damage Health",
      "Regenerate Stamina",
      "Fortify Illusion",
    ],
    obtained: "Dead Trees",
    value: 4,
    weight: 0.3,
    plantable: true,
    fishable: false,
  },
  {
    name: "Mudcrab Chitin",
    effects: [
      "Restore Stamina",
      "Cure Disease",
      "Resist Poison",
      "Resist Fire",
    ],
    obtained: "Mudcrabs",
    value: 2,
    weight: 0.3,
    plantable: false,
    fishable: false,
  },
  {
    name: "Namira's Rot",
    effects: [
      "Damage Magicka",
      "Fortify Lockpicking",
      "Fear",
      "Regenerate Health",
    ],
    obtained: "Caves",
    value: 0,
    weight: 0.3,
    plantable: true,
    fishable: false,
  },
  {
    name: "Netch Jelly",
    effects: ["Paralysis", "Fortify Carry Weight", "Restore Stamina", "Fear"],
    obtained: "Netch",
    value: 20,
    weight: 0.5,
    plantable: false,
    fishable: false,
  },
  {
    name: "Nightshade",
    effects: [
      "Damage Health",
      "Damage Magicka Regen",
      "Lingering Damage Stamina",
      "Fortify Destruction",
    ],
    obtained: "Graveyards, undead areas",
    value: 8,
    weight: 0.1,
    plantable: true,
    fishable: false,
  },
  {
    name: "Nirnroot",
    effects: [
      "Damage Health",
      "Damage Stamina",
      "Invisibility",
      "Resist Magic",
    ],
    obtained: "Near water",
    value: 10,
    weight: 0.2,
    plantable: false,
    fishable: false,
  },
  {
    name: "Nordic Barnacle",
    effects: [
      "Damage Magicka",
      "Waterbreathing",
      "Regenerate Health",
      "Fortify Pickpocket",
    ],
    obtained: "Underwater",
    value: 5,
    weight: 0.2,
    plantable: false,
    fishable: false,
  },
  {
    name: "Orange Dartwing",
    effects: [
      "Restore Stamina",
      "Ravage Magicka",
      "Fortify Pickpocket",
      "Lingering Damage Health",
    ],
    obtained: "Hovering above water",
    value: 1,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Pearl",
    effects: [
      "Restore Stamina",
      "Fortify Block",
      "Restore Magicka",
      "Resist Shock",
    ],
    obtained: "Satchels; Alchemy Laboratory of a Homestead† Pearl Oyster‡",
    value: 2,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Pine Thrush Egg",
    effects: [
      "Restore Stamina",
      "Fortify Lockpicking",
      "Weakness to Poison",
      "Resist Shock",
    ],
    obtained: "Nests in forests",
    value: 2,
    weight: 0.5,
    plantable: false,
    fishable: false,
  },
  {
    name: "Poison Bloom",
    effects: ["Damage Health", "Slow", "Fortify Carry Weight", "Fear"],
    obtained: "Darkfall Cave",
    value: 5,
    weight: 0.3,
    plantable: false,
    fishable: false,
  },
  {
    name: "Powdered Mammoth Tusk",
    effects: ["Restore Stamina", "Fortify Sneak", "Weakness to Fire", "Fear"],
    obtained: "Giant Camps, Alchemy Laboratory of a Homestead†",
    value: 2,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Purple Mountain Flower",
    effects: [
      "Restore Stamina",
      "Fortify Sneak",
      "Lingering Damage Magicka",
      "Resist Frost",
    ],
    obtained: "Mountain flower clumps",
    value: 2,
    weight: 0.1,
    plantable: true,
    fishable: false,
  },
  {
    name: "Red Mountain Flower",
    effects: [
      "Restore Magicka",
      "Ravage Magicka",
      "Fortify Magicka",
      "Damage Health",
    ],
    obtained: "Mountain flower clumps",
    value: 2,
    weight: 0.1,
    plantable: true,
    fishable: false,
  },
  {
    name: "River Betty",
    effects: [
      "Damage Health",
      "Fortify Alteration",
      "Slow",
      "Fortify Carry Weight",
    ],
    obtained: "Lakes, rivers, streams and fish barrels",
    value: 15,
    weight: 0.3,
    plantable: false,
    fishable: true,
  },
  {
    name: "Rock Warbler Egg",
    effects: [
      "Restore Health",
      "Fortify One-Handed",
      "Damage Stamina",
      "Weakness to Magic",
    ],
    obtained: "Rock Warbler Nest",
    value: 2,
    weight: 0.5,
    plantable: false,
    fishable: false,
  },
  {
    name: "Sabre Cat Tooth",
    effects: [
      "Restore Stamina",
      "Fortify Heavy Armor",
      "Fortify Smithing",
      "Weakness to Poison",
    ],
    obtained: "Sabre Cat, Snowy Sabre Cat",
    value: 2,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Salmon Roe†",
    effects: [
      "Restore Stamina",
      "Waterbreathing",
      "Fortify Magicka",
      "Regenerate Magicka",
    ],
    obtained: "Salmon jumping up falls, Kitchen of a Homestead†",
    value: 5,
    weight: 0.2,
    plantable: false,
    fishable: false,
  },
  {
    name: "Salt Pile",
    effects: [
      "Weakness to Magic",
      "Fortify Restoration",
      "Slow",
      "Regenerate Magicka",
    ],
    obtained: "Merchants, containers, near cooking places",
    value: 2,
    weight: 0.2,
    plantable: false,
    fishable: false,
  },
  {
    name: "Scaly Pholiota",
    effects: [
      "Weakness to Magic",
      "Fortify Illusion",
      "Regenerate Stamina",
      "Fortify Carry Weight",
    ],
    obtained: "Dead birch trees",
    value: 4,
    weight: 0.3,
    plantable: true,
    fishable: false,
  },
  {
    name: "Scathecraw",
    effects: [
      "Ravage Health",
      "Ravage Stamina",
      "Ravage Magicka",
      "Lingering Damage Health",
    ],
    obtained: "Harvested all over Solstheim",
    value: 1,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Silverside Perch",
    effects: [
      "Restore Stamina",
      "Damage Stamina Regen",
      "Ravage Health",
      "Resist Frost",
    ],
    obtained: "Lakes, rivers, streams and fish barrels",
    value: 15,
    weight: 0.3,
    plantable: false,
    fishable: true,
  },
  {
    name: "Skeever Tail",
    effects: [
      "Damage Stamina Regen",
      "Ravage Health",
      "Damage Health",
      "Fortify Light Armor",
    ],
    obtained: "Skeever",
    value: 3,
    weight: 0.2,
    plantable: false,
    fishable: false,
  },
  {
    name: "Slaughterfish Egg",
    effects: [
      "Resist Poison",
      "Fortify Pickpocket",
      "Lingering Damage Health",
      "Fortify Stamina",
    ],
    obtained: "Underwater",
    value: 3,
    weight: 0.2,
    plantable: false,
    fishable: false,
  },
  {
    name: "Slaughterfish Scales",
    effects: [
      "Resist Frost",
      "Lingering Damage Health",
      "Fortify Heavy Armor",
      "Fortify Block",
    ],
    obtained: "Slaughterfish",
    value: 3,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Small Antlers",
    effects: [
      "Weakness to Poison",
      "Fortify Restoration",
      "Lingering Damage Stamina",
      "Damage Health",
    ],
    obtained: "Elk",
    value: 2,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Small Pearl",
    effects: [
      "Restore Stamina",
      "Fortify One-Handed",
      "Fortify Restoration",
      "Resist Frost",
    ],
    obtained: "Pearl Oyster‡",
    value: 2,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Snowberries",
    effects: [
      "Resist Fire",
      "Fortify Enchanting",
      "Resist Frost",
      "Resist Shock",
    ],
    obtained: "Snowberry bush, snowy areas",
    value: 4,
    weight: 0.1,
    plantable: true,
    fishable: false,
  },
  {
    name: "Spawn Ash",
    effects: [
      "Ravage Stamina",
      "Resist Fire",
      "Fortify Enchanting",
      "Ravage Magicka",
    ],
    obtained: "Ash Spawn",
    value: 20,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Spider Egg",
    effects: [
      "Damage Stamina",
      "Damage Magicka Regen",
      "Fortify Lockpicking",
      "Fortify Marksman",
    ],
    obtained: "Spider lairs",
    value: 5,
    weight: 0.2,
    plantable: false,
    fishable: false,
  },
  {
    name: "Spriggan Sap",
    effects: [
      "Damage Magicka Regen",
      "Fortify Enchanting",
      "Fortify Smithing",
      "Fortify Alteration",
    ],
    obtained: "Spriggan",
    value: 15,
    weight: 0.2,
    plantable: false,
    fishable: false,
  },
  {
    name: "Swamp Fungal Pod",
    effects: [
      "Resist Shock",
      "Lingering Damage Magicka",
      "Paralysis",
      "Restore Health",
    ],
    obtained: "Swamps",
    value: 5,
    weight: 0.3,
    plantable: true,
    fishable: false,
  },
  {
    name: "Taproot",
    effects: [
      "Weakness to Magic",
      "Fortify Illusion",
      "Regenerate Magicka",
      "Restore Magicka",
    ],
    obtained: "Spriggan",
    value: 15,
    weight: 0.5,
    plantable: false,
    fishable: false,
  },
  {
    name: "Thistle Branch",
    effects: [
      "Resist Frost",
      "Ravage Stamina",
      "Resist Poison",
      "Fortify Heavy Armor",
    ],
    obtained: "Thistle Plant",
    value: 1,
    weight: 0.1,
    plantable: true,
    fishable: false,
  },
  {
    name: "Torchbug Thorax",
    effects: [
      "Restore Stamina",
      "Lingering Damage Magicka",
      "Weakness to Magic",
      "Fortify Stamina",
    ],
    obtained: "Torchbugs, glowing at night",
    value: 1,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Trama Root",
    effects: [
      "Weakness to Shock",
      "Fortify Carry Weight",
      "Damage Magicka",
      "Slow",
    ],
    obtained: "Harvested from ashen areas of Solstheim",
    value: 1,
    weight: 0.2,
    plantable: false,
    fishable: false,
  },
  {
    name: "Troll Fat",
    effects: ["Resist Poison", "Fortify Two-Handed", "Frenzy", "Damage Health"],
    obtained: "Trolls",
    value: 15,
    weight: 1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Tundra Cotton",
    effects: [
      "Resist Magic",
      "Fortify Magicka",
      "Fortify Block",
      "Fortify Barter",
    ],
    obtained: "High mountains below snow line, tundra",
    value: 1,
    weight: 0.1,
    plantable: true,
    fishable: false,
  },
  {
    name: "Vampire Dust",
    effects: [
      "Invisibility",
      "Restore Magicka",
      "Regenerate Health",
      "Cure Disease",
    ],
    obtained: "Vampires, the Silver Hand",
    value: 25,
    weight: 0.2,
    plantable: false,
    fishable: false,
  },
  {
    name: "Void Salts",
    effects: [
      "Weakness to Shock",
      "Resist Magic",
      "Damage Health",
      "Fortify Magicka",
    ],
    obtained: "Storm Atronach",
    value: 125,
    weight: 0.2,
    plantable: false,
    fishable: false,
  },
  {
    name: "Wheat",
    effects: [
      "Restore Health",
      "Fortify Health",
      "Damage Stamina Regen",
      "Lingering Damage Magicka",
    ],
    obtained: "Grows on farms, containers",
    value: 5,
    weight: 0.1,
    plantable: true,
    fishable: false,
  },
  {
    name: "White Cap",
    effects: [
      "Weakness to Frost",
      "Fortify Heavy Armor",
      "Restore Magicka",
      "Ravage Magicka",
    ],
    obtained: "Mushroom clusters near caves or dungeons",
    value: 0,
    weight: 0.3,
    plantable: true,
    fishable: false,
  },
  {
    name: "Wisp Wrappings",
    effects: [
      "Restore Stamina",
      "Fortify Destruction",
      "Fortify Carry Weight",
      "Resist Magic",
    ],
    obtained: "Wispmother",
    value: 2,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
  {
    name: "Yellow Mountain Flower",
    effects: [
      "Resist Poison",
      "Fortify Restoration",
      "Fortify Health",
      "Damage Stamina Regen",
    ],
    obtained: "Darkfall Cave, Ancestor Glade",
    value: 2,
    weight: 0.1,
    plantable: false,
    fishable: false,
  },
];

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<Ingredient[]>
) {
  res.status(200).json(ingredients);
}
